version: "3"
services:
  # Starts the P/S emulator
  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:316.0.0-emulators
    ports:
      - "8085:8085"
    entrypoint: gcloud beta emulators pubsub start --project test-project --host-port 0.0.0.0:8085
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pubsub:8085"]
      interval: 5s
      timeout: 30s
      retries: 3

  # Creates a topic
  mk-topic:
    image: alpine/httpie
    depends_on:
      pubsub:
        condition: service_healthy
    command: PUT http://pubsub:8085/v1/projects/test-project/topics/scan-topic

  # Creates a subscription
  mk-subscription:
    image: alpine/httpie
    depends_on:
      mk-topic:
        condition: service_completed_successfully
    command: PUT http://pubsub:8085/v1/projects/test-project/subscriptions/scan-sub topic=projects/test-project/topics/scan-topic --ignore-stdin

  # Runs the "scanner"
  scanner:
    depends_on:
      mk-topic:
        condition: service_completed_successfully
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8085
      PUBSUB_PROJECT_ID: test-project
    build:
      context: .
      dockerfile: ./cmd/scanner/Dockerfile

  # ES
  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - cluster.name=es-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    volumes:
      - /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 5s
      timeout: 30s
      retries: 3

  # Runs the "indexer"
  indexer:
    depends_on:
      mk-subscription:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
    environment:
      INDEX_NAME: scan_data
      PUBSUB_PROJECT_ID: test-project
      PUBSUB_EMULATOR_HOST: pubsub:8085
      PUBSUB_SUBCRIPTION_ID: scan-sub
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      LOG_ENABLED: "false"
    build:
      context: .
      dockerfile: ./cmd/indexer/Dockerfile
